name: 💡 Feature Request
description: Suggest a new idea or improvement for the Minecraft mod
title: "[Feature]: "
labels: [enhancement]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 Feature Request
        Thanks for taking the time to share your idea!  
        Please provide as much detail as possible so we can understand and discuss it.

  - type: input
    id: mod_version
    attributes:
      label: Mod Version
      description: Which version of the mod are you currently using?
      placeholder: "e.g. v1.2.3"
    validations:
      required: true

  - type: input
    id: mc_version
    attributes:
      label: Minecraft Version
      description: What version of Minecraft are you running?
      placeholder: "e.g. 1.20.1"
    validations:
      required: true

  - type: textarea
    id: feature_description
    attributes:
      label: Describe the Feature
      description: A clear and concise description of what you want to happen.
      placeholder: "Explain your idea..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Did you think of other solutions or workarounds?
      placeholder: "Another way to solve this could be..."

  - type: textarea
    id: benefits
    attributes:
      label: Why is this feature useful?
      description: Tell us how this would improve the gameplay or experience.
      placeholder: "This feature would help players by..."

  - type: textarea
    id: extra
    attributes:
      label: Additional Context
      description: Add any other context, references, or screenshots to support your idea.
